const MOCK_ACTIVITIES = [
  {
    id: 'mock-1',
    emoji: '🌳',
    titre: 'Balade en nature',
    description: 'Une sortie nature simple et ressourçante près de chez vous.',
    subtitle: 'Profitez de l\'air frais en famille',
    locationName: 'Parc local',
    address: 'À vérifier',
    latitude: null,
    longitude: null,
    distanceMinutes: 'À vérifier',
    distanceLabel: 'À vérifier',
    duree: '1h30',
    durationLabel: '1h30 en famille',
    budget: 'Gratuit',
    priceLabel: 'Gratuit',
    priceAmount: 0,
    type: 'outdoor',
    minAgeLabel: 'Tout âge',
    category: 'Nature',
    mood: ['calme', 'energique'],
    weatherFit: ['sunny', 'cloudy'],
    reservationRequired: false,
    icon: '🌳',
    colorTheme: '#4CAF7D',
    benefit: 'Air frais et déconnexion',
    whyGoodIdea: 'Une sortie simple et ressourçante pour toute la famille.',
    whatToBring: ['Eau', 'Collation', 'Ballon'],
    practicalInfos: ['Accès libre', 'Vérifier les horaires localement'],
    tags: ['gratuit', 'nature', 'famille', 'balade'],
    source: 'mock',
    sourceId: 'mock-1',
  },
  {
    id: 'mock-2',
    emoji: '🏛️',
    titre: 'Visite culturelle',
    description: 'Explorez un musée ou site culturel de votre ville.',
    subtitle: 'Éveiller la curiosité des enfants',
    locationName: 'Musée local',
    address: 'À vérifier',
    latitude: null,
    longitude: null,
    distanceMinutes: 'À vérifier',
    distanceLabel: 'À vérifier',
    duree: '2h',
    durationLabel: '2h en famille',
    budget: 'À vérifier',
    priceLabel: 'À vérifier',
    priceAmount: null,
    type: 'indoor',
    minAgeLabel: 'Dès 5 ans',
    category: 'Culture',
    mood: ['calme', 'creatif'],
    weatherFit: ['any'],
    reservationRequired: false,
    icon: '🏛️',
    colorTheme: '#F0956A',
    benefit: 'Découverte et curiosité',
    whyGoodIdea: 'Idéal pour éveiller la curiosité des enfants par tous les temps.',
    whatToBring: ['Carnet de notes', 'Appareil photo'],
    practicalInfos: ['Vérifier les horaires', 'Tarifs réduits possibles'],
    tags: ['culture', 'famille', 'musée', 'tout-temps'],
    source: 'mock',
    sourceId: 'mock-2',
  },
  {
    id: 'mock-3',
    emoji: '☕',
    titre: 'Pause gourmande',
    description: 'Un café ou salon de thé pour se retrouver en famille.',
    subtitle: 'Un moment de partage autour d\'un goûter',
    locationName: 'Café local',
    address: 'À vérifier',
    latitude: null,
    longitude: null,
    distanceMinutes: 'À vérifier',
    distanceLabel: 'À vérifier',
    duree: '1h',
    durationLabel: '1h en famille',
    budget: 'À vérifier',
    priceLabel: 'À vérifier',
    priceAmount: null,
    type: 'food',
    minAgeLabel: 'Tout âge',
    category: 'Gastronomie',
    mood: ['calme', 'social'],
    weatherFit: ['any'],
    reservationRequired: false,
    icon: '☕',
    colorTheme: '#F6A832',
    benefit: 'Moment de partage',
    whyGoodIdea: 'Un moment simple pour se retrouver autour d\'un bon goûter.',
    whatToBring: ['Bonne humeur'],
    practicalInfos: ['Vérifier les horaires', 'Réservation conseillée le week-end'],
    tags: ['café', 'famille', 'social', 'goûter'],
    source: 'mock',
    sourceId: 'mock-3',
  },
];

module.exports = { MOCK_ACTIVITIES };
